import Footer from '../components/Footer';
import GenerateWallet from '../components/GenerateWallet';
import Header from '../components/Header';

const Home = () => {
  return (
    <div>
      <header>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </header>
      <main>
        <Header />
        <GenerateWallet />
        <Footer />
      </main>
    </div>
  )
}

export default Home
